config/routes.rb
Rails.application.routes.draw do
  resources :time_entries
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :colour)
    end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :set_time_entry, only: [:show, :edit, :update, :destroy]

  # GET /time_entries
  # GET /time_entries.json
  def index
    @time_entries = TimeEntry.includes(:project)
  end

  # GET /time_entries/1
  # GET /time_entries/1.json
  def show
  end

  # GET /time_entries/new
  def new
    @time_entry = TimeEntry.new
  end

  # GET /time_entries/1/edit
  def edit
  end

  # POST /time_entries
  # POST /time_entries.json
  def create
    @time_entry = TimeEntry.new(time_entry_params)

    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to time_entries_url, notice: 'Time entry was successfully created.' }
        format.json { render :show, status: :created, location: @time_entry }
      else
        format.html { render :new }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_entries/1
  # PATCH/PUT /time_entries/1.json
  def update
    respond_to do |format|
      if @time_entry.update(time_entry_params)
        format.html { redirect_to time_entries_url, notice: 'Time entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_entry }
      else
        format.html { render :edit }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_entries/1
  # DELETE /time_entries/1.json
  def destroy
    @time_entry.destroy
    respond_to do |format|
      format.html { redirect_to time_entries_url, notice: 'Time entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_entry
      @time_entry = TimeEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_entry_params
      params.require(:time_entry).permit(:project_id, :begin_at, :end_at, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyDay 2016 | TimeTracker</title>
    <%= csrf_meta_tags %>

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">TimeTracker</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to 'Projects', projects_path %></li>
            <li><%= link_to 'Time Entries', time_entries_path %></li>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer">
      <div class="footer-copyright">
        <div class="container">
          © 2016 Ruby Italia. All Rights Reserved
          <a class="grey-text text-lighten-4 right" href="http://www.rubyday.it/">RubyDay</a>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project, html: { class: "col s12" }) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s8">
      <%= f.text_field :name %>
      <%= f.label :name, class: "#{'active' if project.name.present?}" %>
    </div>

    <div class="col s4">
      <p>
        <%= f.color_field :colour %>
        <%= f.label :colour %>
      </p>
    </div>
  </div>

  <div class="row">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
  <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<% if notice.present? %>
  <div class="card-panel">
    <span class="blue-text text-darken-2"><%= notice %></span>
  </div>
<% end %>

<table class="highlight">
  <thead>
    <tr>
      <th>Name</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td>
          <span class="badge" style="background-color:<%= project.colour %>">&nbsp;</span>
          <%= project.colour %>
        </td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path, class: 'btn' %>

app/views/projects/new.html.erb
<div class="row">
  <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @project.colour %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/time_entries/_form.html.erb
<%= form_for(time_entry, html: { class: "col s12" }) do |f| %>
  <% if time_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_entry.errors.count, "error") %> prohibited this time_entry from being saved:</h2>

      <ul>
      <% time_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s6">
      <%= f.collection_select(:project_id, Project.all, :id, :name) %>
      <%= f.label :project_id %>
    </div>
    <div class="input-field col s3">
      <%= f.datetime_field :begin_at %>
      <%= f.label :begin_at, class: 'active' %>
    </div>
    <div class="input-field col s3">
      <%= f.datetime_field :end_at %>
      <%= f.label :end_at, class: 'active' %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <i class="material-icons prefix">comment</i>
      <%= f.text_area :notes, class: 'materialize-textarea' %>
      <%= f.label :notes, class: "#{'active' if time_entry.notes.present?}" %>
    </div>
  </div>

  <div class="row">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/time_entries/edit.html.erb
<div class="row">
  <%= render 'form', time_entry: @time_entry %>
</div>

app/views/time_entries/index.html.erb
<% if notice.present? %>
  <div class="card-panel">
    <span class="blue-text text-darken-2"><%= notice %></span>
  </div>
<% end %>

<table class="highlight">
  <thead>
    <tr>
      <th>Project</th>
      <th>Begin at</th>
      <th>End at</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_entries.each do |time_entry| %>
      <tr>
        <td>
          <span class="badge" style="background-color:<%= time_entry.project.colour %>">&nbsp;</span>
          <%= time_entry.project.name %>
        </td>
        <td><%= time_entry.begin_at %></td>
        <td><%= time_entry.end_at %></td>
        <td><%= time_entry.notes %></td>
        <td><%= link_to 'Edit', edit_time_entry_path(time_entry) %></td>
        <td><%= link_to 'Destroy', time_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Entry', new_time_entry_path, class: 'btn' %>

app/views/time_entries/new.html.erb
<div class="row">
  <%= render 'form', time_entry: @time_entry %>
</div>

app/views/time_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @time_entry.project.name %>
</p>

<p>
  <strong>Begin at:</strong>
  <%= @time_entry.begin_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @time_entry.end_at %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @time_entry.notes %>
</p>

<%= link_to 'Edit', edit_time_entry_path(@time_entry) %> |
<%= link_to 'Back', time_entries_path %>